V1 - Philipe
philipef-dev/code-challenge-todo-list-frontend-v1 pull request #1
Opened 2024-04-23 19:15 UTC by PhilipeF

2024-05-31 15:34 UTC, hladf commented on src/app/App.tsx
> +import { CreateTaskRoutes } from 'routes/CreateTasksRoutes';
poderia ter agrupado os exports lá no index de src/routes, assim o import aqui ficaria assim:
import { TaskListsRoutes, CreateTaskRoutes } from 'routes';

o que deixaria mais organizado, pois no formato atual ficaria mais dificil de ler em um projeto grande

2024-05-31 15:34 UTC, hladf commented on src/hooks/useTasks.ts
> +    setTasks(tasks.filter((task) => task.id !== taskId));
ainda está mutando/modificando o estado atual fazendo o mesmo trabalho do backend e não tem necessidade disso, poderia fazer um GET novamente de tasks e setar o estado baseado no que vem da api atualizado (loadTasks ali em cima)

2024-05-31 15:34 UTC, hladf commented on src/pages/CreateTask/index.tsx
> +    if (!title.trim() || !description.trim()) {
validação não é responsabilidade do submit, então isso poderia estar em outra função, em outro arquivo, e ser apenas chamado aqui pra organizar mais

2024-05-31 15:34 UTC, hladf commented on src/routes/CreateTasksRoutes.tsx
poderia ter criado um arquivo index.ts nessa pasta que exportaria esses dois arquivos routes, pra centralizar os imports como falei no outro comentário

2024-05-31 15:34 UTC, hladf commented on src/services/api.ts
boa, agora sim ta usando bem a api do json server

2024-06-12 22:20 UTC, hladf requested changes
review feito, ja melhorou bastante, só ficou alguns pontos simples de resolver, tamo quase la!

2024-06-12 22:20 UTC, hladf commented on src/helpers/validate.ts
arquivo poderia chamar `validateTask`, pois imagina se tiver varios validators...

2024-06-12 22:20 UTC, hladf commented on src/pages/CreateTask/index.tsx
> +  const taskData = { title, description };
se o taskData só vai ser usado no submit, então só faz sentido ele ser declarado lá no escopo do handleSubmit

2024-06-12 22:20 UTC, hladf commented on src/pages/CreateTask/index.tsx
> +        await addTodo(taskData);
nesse trecho é que poderia ter declarado o taskData logo depois do `event.preventDefault`

2024-06-14 17:58 UTC, PhilipeF commented on src/helpers/validate.ts
feito

2024-06-14 18:01 UTC, PhilipeF commented on src/pages/CreateTask/index.tsx
> +  const taskData = { title, description };
feito

2024-06-14 18:01 UTC, PhilipeF commented on src/pages/CreateTask/index.tsx
> +        await addTodo(taskData);
feito

2024-06-14 18:01 UTC, PhilipeF commented
subir as correções

2025-01-24 14:47 UTC, merged